# Generated by Django 3.2 on 2023-06-11 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_auto_20230611_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='content',
            field=models.CharField(default='test', max_length=500, verbose_name='content'),
            preserve_default=False,
        ),
    ]
