# Generated by Django 3.2 on 2023-06-12 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_bio_content'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bio',
            table='bio',
        ),
        migrations.AlterModelTable(
            name='certificate',
            table='certificate',
        ),
        migrations.AlterModelTable(
            name='education',
            table='education',
        ),
        migrations.AlterModelTable(
            name='experience',
            table='experience',
        ),
        migrations.AlterModelTable(
            name='skill',
            table='skill',
        ),
    ]
